# Tensors in Tensorflow


In [2]:
# Imports
import tensorflow as tf

In [3]:
# Creating tensors
scalar = tf.constant(7)

# Check dimensions of tensor (ndim)
scalar.ndim

0

In [4]:
# Vector creation
vector = tf.constant([10, 10])

# Check dimension
vector.ndim

1

In [5]:
# create matrix
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float16) # specify the data type
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [6]:
# Creating a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[1, 2, 3],
                       [4, 5, 6]]])
tensor.ndim

3

### Creating tensors using tf.Variable

In [7]:
# recreating the tensor but this time using tf.Variable
tensor_v2 = tf.Variable([10, 7])
tensor_v1 = tf.constant([10, 7])
tensor_v1, tensor_v2

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

### Tensor randomization

In [8]:
# Creating random tensors
random_tensor1 = tf.random.Generator.from_seed(42)
random_tensor1 = random_tensor1.normal(shape= (3, 2))
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.uniform(shape = (3, 2))

random_tensor1, random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>)

### Shuffle tensors

In [9]:
tf.random.shuffle(random_tensor1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193765, -1.8107855 ],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

## Making tensors in different ways

In [10]:
# create a tensor of ones
tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

## Turning Numpy arrays into tensors
* Tensors can be run on a GPU => making it much faster to work with

In [11]:
# Turning Numpy arrays into tensors
import numpy as np

numpy_array = np.arange(1, 25, dtype=np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [12]:
# turning the previous np array into a tf tensor
tensor = tf.constant(numpy_array)
shaped_tensor = tf.constant(numpy_array, shape = (3, 8))
shaped_tensor

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

## Getting information from tensors
Key attributes:
* shape (length)
* rank (number of tensor dimentions)
* axis or dim (particular dimention of a tensor)
* size (total number of items in a tensor)

In [13]:
tensor = tf.zeros(shape = [2, 3, 4, 5])
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Tensor Indexing
* works like indexing in Python

In [15]:
tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
# create a rank 2 tensor
rank2_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
rank2_tensor.ndim

2

In [17]:
# get the last item of each row in the tensor
rank2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [18]:
# adding an extra dimension to the tensor - (this is one way to do it)
upgraded_rank2 = rank2_tensor[..., tf.newaxis] # this means include all the data before and add new axis
upgraded_rank2

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [19]:
# adding an extra dimension to the tensor - (this is another way to do it)
tf.expand_dims(rank2_tensor, axis = -1) # inserts another axis at the end

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

# Tensor Operations

In [20]:
# addition
new_tensor = tf.constant([[1, 2], [3, 4]])
new_tensor += 1 
new_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [21]:
# multiplication
new_tensor *= 10
tf.multiply(new_tensor, 2)
new_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

**!** subtraction and division work just the same as they usually do

## Matrix multiplication with tensors

1. Inner dimension must match

In [22]:
# multiplication using tf.matmul => returns the dot product of the tensors
tensor = tf.constant([[1, 2], [3, 4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [23]:
# multiplication using python syntax (@)
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [24]:
# multiplication on different dimension tensors


Multiply with dimension being different

In [25]:
x_tensor = [[1, 2, 3],
            [4, 5, 6]]
y_tensor = [[1, 2],
            [3, 4],
            [5, 6]]

# change shape of tensor
tf.reshape(y_tensor, shape = (2, 3)) @ y_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [26]:
tf.matmul(tf.reshape(y_tensor, shape = (2, 3)), y_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [27]:
# can also reshape using transpose, but they are different
tf.transpose(y_tensor), tf.reshape(y_tensor, shape = (2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

## Tensor aggregation

In [28]:
# get the absolute values
abs_tensor = tf.constant([[-1., -2.], [-3., -4.]])
tf.abs(abs_tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

* get minimum
* get maximum
* get mean
* get sum

In [29]:
tf.reduce_min(abs_tensor), tf.reduce_max(abs_tensor), tf.reduce_mean(abs_tensor), tf.reduce_sum(abs_tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=-4.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-10.0>)

**Exercise**: find varinace and std deviation of the tensor 

In [30]:
# tensor variance
tf.nn.moments(abs_tensor, [0])

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-2., -3.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>)

In [31]:
# Variance usign tfp
import tensorflow_probability as tfp
tfp.stats.variance(abs_tensor)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [32]:
# tensor standard deviation
tf.math.reduce_std(abs_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=1.118034>

## Positional minimum and maximum

In [33]:
# make new tensor to play around with
tf.random.set_seed(42)
pos_tensor = tf.random.uniform(shape=[50])
pos_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [34]:
# positional max
tf.argmax(pos_tensor) # return index

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [35]:
# index on the largest value
pos_tensor[tf.argmax(pos_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [36]:
#positional min
tf.argmin(pos_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [37]:
# index on the smalles value
pos_tensor[tf.argmin(pos_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Tensor Squeezing

In [38]:
sq_tensor = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))
sq_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [39]:
sq_tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [40]:
squeezed_tensor = tf.squeeze(sq_tensor) # removes all extra dimensions
squeezed_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [41]:
squeezed_tensor.shape

TensorShape([50])

## One-hot encoding Tensors

In [42]:
# indices list
ind_list = [0, 1, 2] # red, green, blue

tf.one_hot(ind_list, depth=3) # can also change the matrix values using on_value and off_value parameters

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

# Enable GPU computation on Colab

In [44]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [45]:
# check what GPU are we running our code on
!nvidia-smi

Fri Aug  6 15:25:32 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    71W / 149W |    124MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------